<?php include 'header.phtml' ?> 
	<div id="middle">
		<div class="middletitle">Edit Dropdown</div>
		<div style="height:20px;">&nbsp;</div>
		<div>
			<form method="POST" action="<?php echo $this->url() ?>">
			    <div>
			      <p class="middletitle">
			        <input type="text" name="rt_types" value="<?php echo $this->dtype['rt_types'];?>"/>
			        <button type='submit'><?php echo $this->translate("Save") ?></button>
			        <?php echo $this->translate("or") ?>
			        <a href="/app/public/index/editdropdowntypes">
			          <?php echo $this->translate("cancel") ?>
			        </a>
			      </p>
			    </div>
		  </form>
		</div>
	</div>

<?php include 'footer.phtml' ?> 