<?php include 'header.phtml' ?> 
	<div id="middle">
		<div class="middletitle"><?php echo $this->label?> Vehicle</div>
		<div style="height:20px;">&nbsp;</div>
		<div>
			<?php echo $this->form?>
		</div>
		<div style="padding-left:200px">
		<?php if($this->form->image->getValue()) {?>
			<image src="/images/<?php echo $this->form->image->getValue(); ?>" alt="" width="200px" height="100px"></image>
			<br />
			<br />
			<br />
		<?php }?>
			<br />
		</div>
	</div>
   
<?php include 'footer.phtml' ?> 