<?php include 'header.phtml' ?> 
	<div id="middle">
		<div class="middletitle">Edit Controlled List</div>
		<div class="middletitle">Field Name <input type="text" id="text" value="rt_dropdown_types" readonly = "readonly" ></div>
		<div class="middletitle" style='height:100px'>
			<?php echo $this->form?>
		</div>
		<div class="middletitle">
		<br />
		<span >Existing Values</span>
		<table cellpadding="2" cellspacing="0" width="50%" class="manageTable">
			<tr bgcolor="#9E9A9A" class="tableHeader">
				<td>Types</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
		<?php foreach ($this->results as $row): ?>
		<tr>
			<td>
				<?php echo $row['description'];?>
			</td>
			<td><a href="<?php echo $this->url(array('action' => 'editdropdowndescription','id' => $row['id_desp']));?>">Edit</a></td>
			<td><a href="<?php echo $this->url(array('action' => 'deletedropdowndescription','id' => $row['id_desp']));?>">Delete</a></td>
		</tr>
		<?php endforeach; ?>
		</table>
		</div> 
		<div style="height:20px;">&nbsp;</div>
		
	</div>

<?php include 'footer.phtml' ?> 