<link href="/app/public/css/main.css" media="screen, projection" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/app/public/js/prototype.js">
</script> 


<script type="text/javascript">
function AutoFillModel(value)
{
	$('bg_model_id').empty();

	var elSel = document.getElementById('bg_model_id');
	var i;
	for (i = elSel.length - 1; i>=0; i--) {
	      elSel.remove(i);
	}
	var elSel = document.getElementById('bg_submodel_id');
	var i;
	for (i = elSel.length - 1; i>=0; i--) {
	      elSel.remove(i);
	}
	$('bg_submodel_id').options[0] = new Option("Select or Leave blank", "");
	$('bg_model_id').options[0] = new Option("Loading...", "");
        new Ajax.Request(
        "/app/public/index/populatemodel",
            {
                method:'get',
                parameters: {id: value},
                onSuccess: FillModel
        });
}

function AutoFillModelSearch(value)
{
	$('model').empty;
	$('submodel').empty();

	var elSel = document.getElementById('model');
	var i;
	for (i = elSel.length - 1; i>=0; i--) {
	      elSel.remove(i);
	}
	var elSel = document.getElementById('submodel');
	var i;
	for (i = elSel.length - 1; i>=0; i--) {
	      elSel.remove(i);
	}
	$('submodel').options[0] = new Option("Select or Leave blank", "");   
  	
	$('model').options[0] = new Option("Loading...", "");
        new Ajax.Request(
        "/app/public/index/populatemodel",
            {
                method:'get',
                parameters: {id: value},
                onSuccess: FillModelSearch
        });
}
function FillModelSearch(rsp)
{
	$('model').empty();
	$('submodel').empty();
  	var models = rsp.responseText.split(';');
  	for(var i=0; i<models.length-1; i++)
  	{
  		var model = models[i].split('~');
  		$('model').options[i] = new Option(model[1], model[0]);
  	}
}
function FillModel(rsp)
{
	$('bg_model_id').empty();
  	var models = rsp.responseText.split(';');
  	for(var i=0; i<models.length-1; i++)
  	{
  		var model = models[i].split('~');
  		$('bg_model_id').options[i] = new Option(model[1], model[0]);
  	}
}
function AutoFillSubModel(value)
{
	var year_id = $('bg_year_id').value;
	$('bg_submodel_id').empty();

	var elSel = document.getElementById('bg_submodel_id');
	var i;
	for (i = elSel.length - 1; i>=0; i--) {
	      elSel.remove(i);
	}
	
	$('bg_submodel_id').options[0] = new Option("Loading...", "");
        new Ajax.Request(
        "/app/public/index/populatesubmodel",
            {
                method:'get',
                parameters: {yearid: year_id, modelid: value},
                onSuccess: FillSubModel
        });
}

function FillSubModel(rsp)
{
	$('bg_submodel_id').empty();
  	var sub_models = rsp.responseText.split(';');
  	for(var i=0; i<sub_models.length-1; i++)
  	{
  		var sub_model = sub_models[i].split('~');
  		$('bg_submodel_id').options[i] = new Option(sub_model[1], sub_model[0]);
  	}
} 
function AutoFillSubModelSearch(value)
{
	var year_id = $('year').value;
	
	$('submodel').empty();

	var elSel = document.getElementById('submodel');
	var i;
	for (i = elSel.length - 1; i>=0; i--) {
	      elSel.remove(i);
	}
	
	$('submodel').options[0] = new Option("Loading...", "");
        new Ajax.Request(
        "/app/public/index/populatesubmodel",
            {
                method:'get',
                parameters: {yearid: year_id, modelid: value},
                onSuccess: FillSubModelSearch
        });
}
function FillSubModelSearch(rsp)
{
	$('submodel').empty();
  	var sub_models = rsp.responseText.split(';');
  	for(var i=0; i<sub_models.length-1; i++)
  	{
  		var sub_model = sub_models[i].split('~');
  		$('submodel').options[i] = new Option(sub_model[1], sub_model[0]);
  	}
}
var isIE = document.all?true:false;

if (/Firefox[\/\s](\d+\.\d+)/.test(navigator.userAgent)){ //test for Firefox/x.x or Firefox x.x (ignoring remaining digits);
	isNS = true;
}

function onlyDigits(e) 
{
    var _ret = true;

    if(e.keyCode == 8 || e.keyCode == 9)
        	return true;
    if (e.keyCode < 48 || e.keyCode > 57 ) {
    _ret = false;
    }
   
    return (_ret); 
}

function onlyFloat(e, val)
{ 
	var floatPoint = false;
	for(var i=0; i<=val.length; i++)
	{
		var c = val.charAt(i);
		
		if(c == ".")
		{
			floatPoint = true;
			break;
		}
	}
	if(e.keyCode == 190)
	{
		if(floatPoint == false)
			return true;
		else
			return false;  
	}
	if(e.keyCode == 8 || e.keyCode == 9)
        	return true;
	if (e.keyCode < 48 || e.keyCode > 57) {
	    return false;
	 }
} 

</script>
<div id="content">
	<div id="top">
		<div id="logo">
		</div>
		<div class="headTitle">Road Test Adminstration Interface</div>
		<div class="headRight">
				<div class="headLink">User: <a href="#">Admin</a>&nbsp;|&nbsp;<a href="/app/public/index/signout/">Signout</a></div>
				<div class="headLink"><a href="/app/public/index/">Find Vehicle</a>&nbsp;|&nbsp;<a href="/app/public/index/add/">Add Vehicle</a>
				&nbsp;|&nbsp;<a href="/app/public/index/manageconrolledlist/">Manage Controlled List</a>
				</div>
			</div>
	</div>