<link href="/app/public/css/main.css" media="screen, projection" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/app/public/js/prototype.js">
</script>
<script type="text/javascript">
function AutoFillModel(value)
{
	$('bg_model_id').empty();
	$('bg_model_id').options[0] = new Option("Loading...", "0");
        new Ajax.Request(
        "/app/public/index/populatemodel",
            {
                method:'get',
                parameters: {id: value},
                onSuccess: FillModel
        });
}

function FillModel(rsp)
{
	$('bg_model_id').empty();
  	var models = rsp.responseText.split(';');
  	for(var i=0; i<models.length-1; i++)
  	{
  		var model = models[i].split('~');
  		$('bg_model_id').options[i] = new Option(model[1], model[0]);
  	}
}
function AutoFillSubModel(value)
{
	$('bg_submodel_id').empty();
	$('bg_submodel_id').options[0] = new Option("Loading...", "0");
        new Ajax.Request(
        "/app/public/index/populatesubmodel",
            {
                method:'get',
                parameters: {yearid: value},
                onSuccess: FillSubModel
        });
}

function FillSubModel(rsp)
{
	$('bg_submodel_id').empty();
  	var sub_models = rsp.responseText.split(';');
  	for(var i=0; i<sub_models.length-1; i++)
  	{
  		var sub_model = sub_models[i].split('~');
  		$('bg_submodel_id').options[i] = new Option(sub_model[1], sub_model[0]);
  	}
} 
function addNewItem()
{
	// Retrieve the elements from the document body
	var textbox = document.getElementById('rt_types');
	var listbox = document.getElementById('existing');

	if(textbox.value != '')
	{
		// Now we need to create a new 'option' tag to add to MyListbox
		var newOption = document.createElement('option');
		newOption.value = textbox.value; // The value that this option will have
		newOption.innerHTML = textbox.value; // The displayed text inside of the <option> tags
	 
		// Finally, add the new option to the listbox

		listbox.appendChild(newOption);
		textbox.value = null;
	}
}
function removeItem(selectbox)
{
	var i;
	for(i=selectbox.options.length-1;i>=0;i--)
	{
		if(selectbox.options[i].selected)
		selectbox.remove(i);
	}
}
</script>
<div id="content">
	<div id="top">
		<div id="logo">
		</div>
		<div class="headTitle">Adminstration Interface</div>
		<div class="headRight">
				<div class="headLink">User: <a href="#">Admin</a>&nbsp;|&nbsp;<a href="#">Signout</a></div>
				<div class="headLink"><a href="/app/public/index/">Find Vehicle</a>&nbsp;|&nbsp;<a href="/app/public/index/add/">Add Vehicle</a>
				&nbsp;|&nbsp;<a href="/app/public/index/manageconrolledlist/">Manage Controlled List</a>
				</div>
			</div>
	</div>