<link href="/app/public/css/main.css" media="screen, projection" rel="stylesheet" type="text/css" />

<div id="content">
	<div id="top">
		<div id="logo">
		</div>
		<div class="headTitle">Adminstration Interface</div>
		<div class="headRight">
				<div class="headLink">User: <a href="#">Admin</a>&nbsp;|&nbsp;<a href="#">Signout</a></div>
				<div class="headLink"><a href="/app/public/index/">Find Vehicle</a>&nbsp;|&nbsp;<a href="/app/public/index/add/">Add Vehicle</a>
				&nbsp;|&nbsp;<a href="#">Manage Controlled List</a>
				</div>
			</div>
	</div>
	<div id="middle">
		<div class="middletitle">Find Vehicle</div>
		<div class="middleLeft">
			<?php echo $this->form?>
		</div>
		<div class="middleSeperator">- or -</div>
		<div class="middleRight">
			<?php echo $this->formright?>
		</div>
		
		<div class="results">	
		<table  cellpadding="5" cellspacing="0" class="dataTable">
			<tr bgcolor="#9E9A9A">
				<td>ID</td>
				<td>Published</td>
				<td>Year</td>
				<td>Make</td>
				<td>Model</td>
				<td>bg_make_id</td>
				<td>bg_model_id</td>
				<td>bg_submodel_id</td>
				<td style="border-right:1px solid #9E9A9A">bg_year_id</td>
			</tr>
			<?php foreach ($this->paginator as $row): ?>
				<tr>
					<td><?php echo $row['id']?></td>
					<td><?php if(!empty($row['rt_published']))echo $row['rt_published']; else echo "-";?></td>
					<td><?php if(!empty($row['rt_model_year']))echo $row['rt_model_year']; else echo "-";?></td>
					<td><?php if(!empty($row['rt_controlled_make']))echo $row['rt_controlled_make']; else echo "-";?></td>
					<td><?php if(!empty($row['rt_model']))echo $row['rt_model']; else echo "-";?></td>
					<td><?php if(!empty($row['bg_make_id']))echo $row['bg_make_id']; else echo "-";?></td>
					<td><?php if(!empty($row['bg_model_id']))echo $row['bg_make_id']; else echo "-";?></td>
					<td><?php if(!empty($row['bg_submodel_id']))echo $row['bg_submodel_id']; else echo "-";?></td>
					<td style="border-right:1px solid #9E9A9A"><?php if(!empty($row['bg_submodel_id']))echo $row['bg_submodel_id']; else echo "-";?></td>
					</tr>
			<?php endforeach; ?>
		</table>
	
		<?php echo $this->paginationControl($this->paginator, 'Elastic', 'controls.phtml'); ?>
		</div>
	</div>
	<div id="bottom">
	</div>
	
	
</div>