
<style>
#document {
    margin: 0 auto;
    min-width: 990px;
    position: relative;
    text-align: left;
    width: 990px;
    font-family:arial;
}

#pallet {
    margin: 0;
}

#pallet {
    height: 110px;
    margin: 0 auto 0px;
    width: 990px;
}

#header {
    margin-top: 10px;
}

#header {
    margin: 0 0 1.4em;
}

#masthead
{
    float: left;
    color: red;
}

#masthead, #masthead a:link, #masthead a:active, #masthead a:visited {
    height: 56px;
    width: 246px;
}

#masthead {
    background: url("images/cdlogo.png") no-repeat scroll 0 0 transparent;
    margin: 17px 16px 17px 0;
    padding-bottom: 10px;
}
.headleft{
	float:left;
	font-weight:bold;
	font-size:18px;
	text-align:center;
	padding-top:34px;
	padding-left:0px;
	font-family:arial;
}
.headright{
	font-weight:bold;
	font-size:12px;
	padding-top:20px;
	font-family:arial;
	color:gray;
}
.title{
	font-weight:bold;
	font-size:15px;
	padding-top:5px;
	font-family:arial;
}
A:link {text-decoration: underline; color: #014B96;}
A:visited {text-decoration: underline; color: #014B96;}
A:active {text-decoration: none; color: #014B96;}
A:hover {text-decoration: none;}
</style>
<link href="/public/css/main.css" media="screen" rel="stylesheet" type="text/css" />

<div id="document">
	<div id="pallet">
		<div id="header">
			<div id="masthead">
			</div>
			<div class="headleft">Adminstration Interface</div>
			<div style="float:right; text-align:right;">
				<div class="headright">User: <a href="#">Admin</a>&nbsp;|&nbsp;<a href="#">Signout</a></div>
				<div class="headright" style="padding-top:20px;"><a href="#">Find Vehicle</a>&nbsp;|&nbsp;<a href="#">Add Vehicle</a>
				&nbsp;|&nbsp;<a href="#">Manage Controlled List</a>
				</div>
			</div>
		</div>
	</div>
	<div class="title">Find Vehicle</div>
	<div style="height:20px;">&nbsp;</div>
	<div style="width:1050px;">
	<?php echo $this->form?>
	</div>
	<div style="float:left">
	&nbsp;<br><br></br>
	</div>
	
	<table  cellpadding="5" cellspacing="0">
		<tr bgcolor="#9E9A9A">
			<td style="border-top:1px solid #9E9A9A; border-left:1px solid #9E9A9A">id</td>
			<td style="border-top:1px solid #9E9A9A; border-left:1px solid #9E9A9A">rt_published</td>
			<td style="border-top:1px solid #9E9A9A; border-left:1px solid #9E9A9A">rt_model_year</td>
			<td style="border-top:1px solid #9E9A9A; border-left:1px solid #9E9A9A">rt_controlled_make</td>
			<td style="border-top:1px solid #9E9A9A; border-left:1px solid #9E9A9A">rt_model</td>
			<td style="border-top:1px solid #9E9A9A; border-left:1px solid #9E9A9A">bg_make_id</td>
			<td style="border-top:1px solid #9E9A9A; border-left:1px solid #9E9A9A">bg_model_id</td>
			<td style="border-top:1px solid #9E9A9A; border-left:1px solid #9E9A9A">bg_submodel_id</td>
			<td style="border-top:1px solid #9E9A9A; border-left:1px solid #9E9A9A; border-right:1px solid #9E9A9A">bg_year_id</td>
		</tr>
		<?php foreach ($this->paginator as $row): ?>
			<tr>
				<td style="border-top:1px solid #9E9A9A; border-left:1px solid #9E9A9A"><?php echo $row['id']?></td>
				<td style="border-top:1px solid #9E9A9A; border-left:1px solid #9E9A9A"><?php if(!empty($row['rt_published']))echo $row['rt_published']; else echo "-";?></td>
				<td style="border-top:1px solid #9E9A9A; border-left:1px solid #9E9A9A"><?php if(!empty($row['rt_model_year']))echo $row['rt_model_year']; else echo "-";?></td>
				<td style="border-top:1px solid #9E9A9A; border-left:1px solid #9E9A9A"><?php if(!empty($row['rt_controlled_make']))echo $row['rt_controlled_make']; else echo "-";?></td>
				<td style="border-top:1px solid #9E9A9A; border-left:1px solid #9E9A9A"><?php if(!empty($row['rt_model']))echo $row['rt_model']; else echo "-";?></td>
				<td style="border-top:1px solid #9E9A9A; border-left:1px solid #9E9A9A"><?php if(!empty($row['bg_make_id']))echo $row['bg_make_id']; else echo "-";?></td>
				<td style="border-top:1px solid #9E9A9A; border-left:1px solid #9E9A9A"><?php if(!empty($row['bg_model_id']))echo $row['bg_make_id']; else echo "-";?></td>
				<td style="border-top:1px solid #9E9A9A; border-left:1px solid #9E9A9A"><?php if(!empty($row['bg_submodel_id']))echo $row['bg_submodel_id']; else echo "-";?></td>
				<td style="border-top:1px solid #9E9A9A; border-left:1px solid #9E9A9A; border-right:1px solid #9E9A9A"><?php if(!empty($row['bg_submodel_id']))echo $row['bg_submodel_id']; else echo "-";?></td>
				</tr>
		<?php endforeach; ?>
	</table>
	
</div>