<?php
/**
 * SocialEngine
 *
 * @category   Application_Core
 * @package    Core
 * @copyright  Copyright 2006-2010 Webligo Developments
 * @license    http://www.socialengine.net/license/
 * @version    $Id: privacy.tpl 7244 2010-09-01 01:49:53Z john $
 * @author     Alex
 */
?>
<div class='layout_middle'>
<h2><?php echo $this->translate('PRIVACY POLICY') ?></h2>
<!--<p>
  <?php echo $this->translate('_CORE_PRIVACY_STATEMENT') ?>
</p>-->
<h5>LAST UPDATED: DECEMBER 13, 2010</h5>
<br/>
<p>
<b>Questions.</b> If you have any questions or concerns about our privacy policy, contact our privacy team through this Contact Page 
</p>
<br/>
<p>
Scope. This privacy policy covers all of Momburbia. It does not, however, apply to entities that Momburbia does not own or control, such as applications and websites advertising Momburbia. By using or accessing Momburbia, you agree to our privacy practices outlined here.
</p>
<br/>
<p>
No information from individuals under the age of 16. If you are under the age 16, please do not attempt to register for Momburbia or provide any personal information about yourself to us. If we learn that we have collected personal information from an individual under the age of 16, we will delete that information as quickly as possible. If you believe that we might have any information from an individual under age 16, please contact us through this Contact Page
</p>
<br/>
<p>
At Momburbia&reg;, we are committed to maintaining your privacy and your trust. This Privacy Policy explains how we collect, protect, use and share information about you when you use the Momburbia website (the "Site"). We hope this information increases your confidence in Momburbia and enhances your experience on our Site. This Privacy Policy is incorporated into and subject to the Momburbia Terms of Service.  Each time that you use the Site, you signify that you agree to be bound by the Terms of Service and this Privacy Policy. If you do not agree to the terms of this Privacy Policy, you must discontinue using the Service and terminate your membership.
</p>
<br/>
<p>
ABOUT MOMBURBIA
Momburbia is an online service for moms that allows our mom members to set up unique personal profiles and, through those profiles, to create an online network of other moms. Momburbia members ("Members") can view each others' profiles, communicate with old friends and make new friends on the Site, share photos, post blogs and comments, and describe their interests. To enrich our Members' experience, we request and display some personal information to other Members and visitors, which allows our users to identify each other and expand their network of friends. Momburbia members can change their profile information at any time and can control how other Members and Momburbia communicates with them.
</p>
<br/>
Information you provide to us:

Information About Yourself. When you sign up for Momburbia you provide us with your email, profile address, name, city, country, birth date. You may also register using Facebook Connect.  During the registration process we give you the opportunity to connect with your friends. You will also be able to add a picture of yourself. In some cases we may ask for additional information for security reasons or to provide specific services to you. Once you register you can provide other information about yourself by connecting with, for example, relationships, activities and interests.   You can also provide personal information about yourself, such as your political and religious views.

Content. One of the primary reasons people use Momburbia is to share content with others. Examples include when you update your status, upload or take a photo, share a link, create an event or a group, make a comment, write something on someone’s Wall, write a blog, or send someone a message. 
Friend Information. We offer contact importer tools to help you upload your friends’ addresses so that you can find your friends on Momburbia, and invite your contacts who do not have Momburbia accounts to join. If you give us your password to retrieve those contacts, we will not store your password after you have uploaded your contacts’ information.
Information we collect when you interact with Momburbia:
Site activity information. We keep track of some of the actions you take on Momburbia, such as adding friends (including joining a group or adding a friend), creating a photo album, sending a message, inviting another user, indicating you "like" a post, attending an event or connecting/logging in using Facebook. In some cases you are also taking an action when you provide information or content to us. For example, if you share a video, in addition to storing the actual content you uploaded, we might log the fact that you shared it.
Access Device and Browser Information. When you access Momburbia from a computer, mobile phone, or other device, we may collect information from that device about your browser type, location, and IP address, as well as the pages you visit.
Cookie Information. We use "cookies" (small pieces of data we store for an extended period of time on your computer, mobile phone, or other device) to make Momburbia easier to use, to make our advertising better, and to protect both you and Momburbia. For example, we use them to store your login ID (but never your password) to make it easier for you to login whenever you come back to Momburbia. We also use them to confirm that you are logged into Momburbia, and to know when you are interacting with Facebook Connect, our widgets, share buttons, and our advertisements. You can remove or block cookies using the settings in your browser, but in some cases that may impact your ability to use Momburbia.
Web Beacons. Our Web pages and our e-mail newsletters contain "web beacons." Web beacons allow us to count users that have visited a web page or opened an email that contains a web beacon and collect other types of aggregate information. Using this information, we are able to measure the effectiveness of our advertising and how visitors use our Site. This allows us to learn what pages are most attractive to our visitors, which parts of our Site are the most interesting and what kind of offers our Members like to see. Some of the web beacons that are in place on our Site are used only by Momburbia, and other web beacons are from our vendors and advertisers who use this data to assist us in analyzing how our Members use the Site. In addition, we have agreements with various affiliate networks that promote Momburbia on their affiliate websites. These affiliate advertisers may use web beacons in their advertisements to track users who click through from the affiliate website to the Site.

Information we receive from third parties:
Facebook Connect. We do not own or operate the applications or websites that you use through Facebook (such as games and utilities). Whenever you login or register to Momburbia using Facebook Connect, we will receive information from them, including information about actions you take.
Information from other websites. We may institute programs with advertising partners and other websites in which they share information with us: 
			We may ask advertisers to tell us how our users responded to the ads we showed them (and for comparison purposes, how other users who didn’t see the ads acted on their site). This data sharing, commonly known as "conversion tracking," helps us measure our advertising effectiveness and improve the quality of the advertisements you see.
			We may receive information about whether or not you’ve seen or interacted with certain ads on other sites in order to measure the effectiveness of those ads.

Information from other users. We may collect information about you from other Momburbia users, such as when a friend tags you in a photo or provides friend details, or indicates a relationship with you.
From time to time we may ask you to respond to surveys or other requests for information and we collect the information you provide. We may collect information from you when you participate in sweepstakes and promotions offered on our Site. We may also collect information about you through other methods, including research surveys or information we obtain from third parties, including verification services, data services, as well as public sources. We use this information to continually offer you the most value as a Momburbia Member.
All personally identifiable information that we collect may become part of your Momburbia Member file and may be used by Momburbia as provided in this Privacy Policy or as disclosed at the time you provide the information or as otherwise agreed by you.
Sharing information on Momburbia. This section explains how your privacy settings work, and how your information is shared on Momburbia.  You should always consider your privacy settings before sharing information on Momburbia.
Personal Information.  Your personal information is controlled within the privacy settings.  You are able to control how Members will view your profile.  If you do not wish to share certain types of profile information, it is better to leave it blank or change your privacy settings to allow only Member groups you are comfortable with.
Gender and Birth Date.  In addition to name and email address, we require you to provide your birth date during the registration process.  We ask for your date of birth to verify that you are 16 or older, and so that we can better limit your access to content and advertisements that are not age appropriate.  Because your date of birth is required, you cannot delete them.  
Other.  Here are some other things to remember: 
			Some of the content you share and the actions you take will show up on your friends’ home pages and other pages they visit.
			Even after you remove information from your profile or delete your account, copies of that information may remain viewable elsewhere to the extent it has been shared with others, it was otherwise distributed pursuant to your privacy settings, or it was copied or stored by other users.
			You understand that information might be reshared or copied by other users.
			Certain types of communications that you send to other users cannot be removed, such as messages.
			When you post information on another user’s profile or comment on another user’s post, that information will be subject to the other user’s privacy settings.
			If you use an external source to publish information to Momburbia (such as a mobile application), you should check the privacy setting for that post, as it is set by that external source.
	
"Everyone" Information. Information set to "everyone" is publicly available information.  Such information may, for example, be accessed by everyone on the Internet (including people not logged into Momburbia), be indexed by third party search engines, and be imported, exported, distributed, and redistributed by us and others without privacy limitations. Such information may also be associated with you, including your name and profile picture, even outside of Momburbia, such as on public search engines and when you visit other sites on the Internet.  The default privacy setting for your profile information you post on Momburbia is set to "everyone." You can review and change the default settings in your privacy settings. If you delete "everyone" content that you posted on Momburbia, we will remove it from your Momburbia profile, but have no control over its use outside of Momburbia.
By using the search functionality on the Site, Momburbia Members can find other moms with similar interests and challenges. When you find other Members, you can view their personal profiles to find out more about them based on the information they have decided to share on the Site.  As a Momburbia Member, you can share personal content, such as classified, blogs and photos. Please be aware that by using any of these features, your personally identifiable information may be accessible to Members and non-Members, and Momburbia has no control over how those users may use your personally identifiable information. We have the right, but not the obligation, to monitor any activity and content associated with the public and private forums and interactive areas on our Site. Please review our Terms of Service for more information regarding your appropriate use of these areas.
Email and Newsletters. Momburbia may send you service-related announcements and emails from time to time. For instance, if a friend sends you a message or someone comments on your photos or blog, you may receive an email alerting you to that fact. We may also use your information to send you e-newsletters, updates and communications about Momburbia. You may opt-out to the newsletters directly from the email you receive.  
Sweepstakes and Promotions. On occasion, we offer sweepstakes and other promotions in conjunction with a sponsor. By participating in a promotion, you submit to that promotion's terms and conditions including providing us with permission, if required, to share your personally identifiable information with a particular sponsor.
Third Party Offers. On occasion, we are able to offer you special products or services through a relationship with a third party. In those cases, the offer will be brought to you by Momburbia and fulfilled by the third party. If you accept the offer, you will become a customer of the company that is fulfilling the offer and we will not have control over their use of the personally identifiable information that you provide to them when you accept the offer.
Invite a Friend. If you do become a Member, not only can you enjoy all of the benefits of membership, but you can also invite other individuals to join by providing us with their email addresses. Using the information you give us on these potential Members, we will send them an email invitation to join Momburbia. The only way these individuals can become Members, however, is if they come to our Site and sign up themselves. We do not use this information for other purposes.
Legal Matters; Safety. We may, without your consent, access and disclose your information, any communications sent or received by you, and any other information that we may have about you or your account as may be permitted or required by law (including, but not limited to, court order or subpoena), or to prevent or investigate suspected fraud, violations of our Terms of Service, or activity that appears to us to be illegal or may expose us to legal liability. Additionally, we may disclose your information in situations that we believe to be emergencies involving potential threats to the physical safety of any person or property if we believe that your information in any way relates to that threat.
Sale of Business or Assets. In the event that Momburbia, substantially all of its assets, or a line of business are acquired or merged with another company, personally identifiable information of our Members may be one of the assets sold or merged in connection with that transaction. Momburbia will notify users of the Site of such a change in ownership or transfer of assets by posting a notice on the Site.
Third Party Ad Servers. We may use third party advertising technology to serve ads when you visit our Site. For instance, we may use Google AdSense, among others, to provide advertising in our e-newsletters. If your browser is set up to accept cookies, DoubleClick, Google AdSense and some of Momburbia Name's advertisers and partners may place cookies or web beacons on your computer when you visit our Site or interact with our email messages. Please note that this happens whether or not you click on an advertisement placed by these companies. DoubleClick, Google AdSense and Momburbia's advertisers and partners use cookies and web beacons according to their own privacy and security polices which you can find on their websites.
V. IMPORTANT DISCLOSURES, PRACTICES AND CONTACT INFORMATION
Momburbia contains links to other sites. It is possible for you to receive information directly from our partners and other companies if you access them through a link on Momburbia.com or if you go directly to their Websites. Once you are on their sites, any data that you supply to these partners, for example, to obtain information or buy products directly from them is beyond our reach and will be the responsibility of each of the linked-to entities and not Momburbia. We are not responsible for the privacy practices or the content of these Websites or any other sites linked to or referenced on our Site.
Security. Momburbia has multiple layers of security on its systems. We have implemented software and hardware security, including firewalls, data encryption, and private networks intended to protect your personally identifiable information from unauthorized access. We use firewalls and intrusion-detection devices that are designed to defend against hackers and notify us if any attempts are made to compromise our network. We regularly review additional software upgrades to enhance our security measures. However, despite our efforts, no system can completely guaranty that there will never be unauthorized access to your personally identifiable information, and your use of the Site indicates that you are willing to assume this risk.
A Note About International Users. The Momburbia Site is hosted in the United States. If you are using the Site from outside the United States, by providing your information to this Site, you are consenting to the transfer of your information to the United States for processing and maintaining in accordance with this Privacy Policy and our Terms of Use. 
Children's Privacy. Momburbia does not encourage participation or visitation by children. Visitors who are known to be under the age of 16 are prohibited from becoming Momburbia Members. Momburbia does not knowingly collect personally identifiable information from children under the age of 16.
Changes to the Privacy Policy. We may change this Privacy Policy from time to time. The most recent version of the Privacy Policy will always be posted on the Site, with the "Effective Date" posted at the top of the Policy. We will inform you if we substantially modify the way we handle your personally identifiable information by posting a notice on the Site, and we will give you the opportunity to opt-out of such differing uses.
How You Can Change or Remove 
Information editing your profile. You may change or remove your profile information at any time by going to your profile page and clicking "Edit My Profile." Information will be updated immediately.
Deactivating or deleting your account. If you want to stop using your account you may delete it.  When you delete an account, it is permanently deleted from Momburbia. You should only delete your account if you are certain you never want to reactivate it.
Limitations on removal. Even after you remove information from your profile or delete your account, copies of that information may remain viewable elsewhere to the extent it has been shared with others, it was otherwise distributed pursuant to your privacy settings, or it was copied or stored by other users. However, your name will no longer be associated with that information on Momburbia. Additionally, we may retain certain information to prevent identity theft and other misconduct even if deletion has been requested. If you have given third party applications or websites access to your information, they may retain your information to the extent permitted under their terms of service or privacy policies.  But they will no longer be able to access the information through our Platform after you disconnect from them.
Contacting Us. If you have any questions about this Privacy Policy, or the practices of this Site, please visit our Contact Page

</div>