<?php
/**
 * SocialEngine
 *
 * @category   Application_Core
 * @package    Core
 * @copyright  Copyright 2006-2010 Webligo Developments
 * @license    http://www.socialengine.net/license/
 * @version    $Id: terms.tpl 7244 2010-09-01 01:49:53Z john $
 * @author     John
 */
?>
<div class='layout_middle'>
<h2><?php echo $this->translate('Terms of Service') ?></h2>
<!--<p>
  <?php echo $this->translate('_CORE_TERMS_OF_SERVICE') ?>
</p>-->
<h5>LAST UPDATED: DECEMBER 13, 2010</h5>
<br/>
<div class="terms">
<p align="justify"><b>PLEASE READ THE FOLLOWING TERMS OF SERVICE RELATING TO YOUR USE OF THE MOMBURBIA WEBSITE CAREFULLY. THESE TERMS OF SERVICE GOVERN YOUR USE OF THE MOMBURBIA WEBSITE AND ALL SERVICES OFFERED THROUGH THE WEBSITE.</b></p><br/>
<p align="justify">These Terms of Service ("TOS") apply to all users of the Momburbia&trade; website (the "Site"). The term the "Site" as it is used in these TOS includes access via any wireless device, including any optimized version of the Site accessed through Momburbia Mobile. By using this Site (including any content posted on the Site), you signify your acceptance of these TOS, as well as the <a href='/index.php/help/guide'>Community Guidelines</a> and the <a href='/index.php/help/privacy'>Momburbia Privacy Policy</a>, which are incorporated by reference into these TOS and made a part hereof. Momburbia reserves the right to update or change these TOS at any time by posting the most current version of the TOS on the Site. Your continued use of the Site after we post any changes to the TOS signifies your agreement to any such changes. If you do not agree to these TOS, you must discontinue using the Site and terminate your membership in Momburbia. This Site is owned and operated by Momburbia, Inc.</p><br/>
<p align="justify"><b>Website Access.<br/><br/>
THIS IS A WEBSITE FOR MOMS AND SOON-TO-BE MOMS, OFFERING THEM A POSITIVE AND INTERESTING ENVIRONMENT WHERE THEY CAN CONNECT WITH OTHER MOMS, SHARE INFORMATION, MAKE NEW FRIENDS AND DISCUSS ISSUES OF MUTUAL INTEREST. TO USE THIS SITE AND THE SERVICES OFFERED, YOU MUST BE 16 YEARS OLD OR OLDER. BY ACCESSING THIS SITE, YOU ARE CERTIFYING THAT YOU ARE AT LEAST 16 YEARS OF AGE. USE OF THE SITE AND THE SERVICES IS VOID WHERE PROHIBITED.
</b></p><br/>
<p align="justify"><b>Registering as a Member.</b><br/><br/>
You must become a member to enter the Momburbia Site.  Members can access most of the most popular features and services that Momburbia offers, such as blogs, photos, groups, private messages, social networking features, or other services that we may offer in the future (the "Services"). Registration is free. 
</p><br/>
<p align="justify">When you register with Momburbia, you will be asked to provide us with your name, birthday, email address and other information that we may request, all of which will become part of your profile ("Profile Data"), and which you can add to or change from time to time. You will also be asked to select a profile address and password which will serve to access your home page and allow you to access your account. You may not (i) select or use a profile address of another person with intent to impersonate that person, (ii) use a profile address which another person has rights without authorization from that person, or (iii) use a profile address that Momburbia, at its sole discretion, deems offensive. You agree to provide (i) true, accurate, current and complete information about yourself as prompted by the registration form, and (ii) maintain and properly update the Profile Data to keep it true, accurate, current and complete. If you provide information that is untrue, inaccurate, not current or incomplete, or Momburbia has reasonable grounds to suspect that you have, we have the right to suspend or terminate your membership and refuse any and all current or future use of the Site and the Services (or any portion thereof). Members must immediately notify Momburbia of any known or suspected unauthorized use of a Member's account, or any known or suspected breach of security, including loss, theft, or unauthorized disclosure of Member's password. Members should be cautious about sharing their account information with third parties. Each Member is responsible for the confidentiality of her/his profile address, account and password and all usage or activity on her/his account, including use of the account by any third party, whether or not such use is authorized by the Member. Members may share an account (using one profile address and password) if the account is being used for legitimate group discussions and if it is clearly disclosed that it is a group account.</p><br/>
<p align="justify"><b>How You Can Use the Services.</b><br/><br/>
This Site and the Services offered are intended for your personal, noncommercial use in accordance with these TOS. You agree that you will not (i) copy, display or distribute any part of the Site, in any medium, without Momburbia's prior written consent, or (ii) alter or modify any part of the Site other than as may be reasonably necessary to use the Site for its intended purpose.
</p><br/>
<p align="justify">You further agree that you will not use any automated devices, such as spiders, robots or data mining techniques to catalog, download, store or otherwise reproduce, store or distribute content available on the Site, or to manipulate the Site or the Services, or otherwise exceed the limited access granted to you by Momburbia. You will take no action to interfere with, interrupt, destroy or limit the functionality of the Site or any computer software or hardware or telecommunications equipment. You will not distribute or transmit any content or software or other computer files that contain a computer virus or other harmful component</p><br/>
<p align="justify"><b>Controlling your Personal Information</b><br/><br/>
One of the great features of Momburbia is that you control who will see your profile information as well as any other information or photos that you post on the Site, simply by adjusting your privacy settings. When you first create a profile, or when you make any changes to it, you can select who will see that information. In most cases (there are a few exceptions, described below), you can make your profile information completely private, so that no one sees it but you. You can also choose to make your profile information (or parts of it) visible only to the friends in your network. Or you can choose to make it visible to everyone who visits the Site.
</p><br/>
<p align="justify">You also have control over the personal information you post to the Site through blogs, photos and other features. Each time that you make a post to the Site, you'll be prompted to choose who you want to see that post. You can choose to share photos and posts with your network of friends, or you can choose to share them with everyone. You can change your privacy selection for a particular post at any time by editing the original post/photo and changing the privacy setting in the "Privacy" area of the edit page. However, that change will only affect that particular piece of content. Be aware that if you choose to make your posts visible to everyone, then any personal information you post will be accessible to all Members and all visitors to the Site. You should also be aware that any information that is made public on the Site will be searchable by other search engines. In addition, even if that content is later removed from this Site, it may still be stored in other computers of people who visited the Site, and removal of that information from this Site will not remove it from those other computers. Therefore, we caution you to be very careful about posting personal information to the Site.</p><br/>
<p align="justify">Momburbia makes every effort to ensure that your Profile Data and posts are displayed only to the people you selected in your privacy settings. However, mistakes can happen. If you believe that your content is being displayed in a manner that you did not authorize, you can notify us of the error by using the "Contact Us" button on any page of the Site and we will correct the problem promptly. However, you agree that your sole remedy against us if we were to make such a mistake is to require us to change the privacy settings to those that you originally requested.</p><br/>
<p align="justify"><b>User Submissions</b><br/><br/>
Most of the content on Momburbia is submitted by our Members. We encourage you to take advantage of the many opportunities to interact with Momburbia Members by posting and reading content and participating in online discussions.
</p><br/>
<p align="justify">You acknowledge that by using the Site, you may be exposed to content that you find objectionable, indecent or offensive or which is inaccurate, misleading or incomplete. We are not responsible for the accuracy, completeness or usefulness of any content, nor do we endorse such content. We do not verify the identity of people using our Site. You use the Site and the content at your own risk.</p><br/>
<p align="justify">All content that you post to Momburbia must comply with these TOS and the <a href='/index.php/help/guide'>Momburbia Community Guidelines</a>. You take sole responsibility for all content that you post on the Site and the consequences of posting that content. You are responsible for obtaining all necessary rights to upload, post and distribute the content, including obtaining permission from any person shown in a photo that you upload or identified in any writing that you post. You agree that you will not upload, email, transmit, or otherwise make available any content that is:</p><br/>
	<ul>
	<li>threatening, defamatory, abusive, obscene, pornographic, or any material that would give rise to any civil or criminal liability under applicable law;</li>
	<li>any materials that could infringe any copyright, trademark, publicity or privacy right or any other intellectual property right of any person or entity unless you have first received permission from the owner of those rights to use the materials;</li>
	<li>any materials containing slurs, hate speech or which attack an individual or group on the basis of race, color, religion, national origin, or sexual preferences;</li>
	<li>any materials that contain an email address, telephone number, street address, last name, or any other content or information that identifies a user;</li>
	<li>any materials that constitute spam. Sending the same message multiple times or to multiple people will be treated as spam.</li>
	</ul>
	<br/>
<p align="justify">We permit advertising only in specified areas of the Site that are specifically designated for advertising.</p><br/>
<p align="justify">By submitting content to the Site, you grant to Momburbia and its successors in business a perpetual, worldwide, royalty-free, and non-exclusive license to reproduce, distribute, modify, edit, display, adapt, create derivative works from and market and promote the content, for any commercial purposes, and in any medium now existing or hereinafter developed, and to use your name, likeness and any personal information you submit with the content without your prior approval or the payment of any compensation. You also grant each user of the Momburbia Site a non-exclusive license to access your content as permitted through the functionality of the Site and under these TOS.</p><br/>
<p align="justify"><b>User Conduct.</b><br/><br/>
As an online community, we will thrive only if we can rely on our Members to act responsibly. We believe that all Members and visitors benefit from basic rules for acceptable conduct while using the Site and the Services. These rules have been encoded into our Community Guidelines. By using the Site, you agree to comply with the Community Guidelines.
</p><br/>
<p align="justify"><b>Our Content Removal Rights.</b><br/><br/>
We reserve the right, but not the obligation, to monitor, edit or remove any content at any time and without notice if we believe that <br/><br/>
(i) the content violates these TOS or the Community Guidelines, <br/>
(ii) removal is necessary to protect the rights, property or personal safety of Momburbia, its users and the public, or <br/>
(iii) if required to do so by law. We also reserve the right to remove postings that are off the subject or not in English. We can also remove content if we believe that doing so will improve our Site and the experience of our Members.
</p><br/>
<p align="justify">If you belief that any postings on the Site violate these TOS or the Community Guidelines, please let us know by using the "Report this post" which can be found on many pages of the Site. We try to review all reported violations and, if we agree with you, we'll take appropriate action. However, in all cases, we are the final judge on whether these TOS or Community Guidelines have been violated and we will determine what, if any, action should be to taken.</p><br/>
<p align="justify">Notwithstanding anything to the contrary stated herein or in our Privacy Policy, we have the right to view and monitor any content posted to this Site, even if that content has been designated as "private," if we have reason to believe that the content or the Member posting the content has violated these TOS or the incorporated Community Guidelines, or has engaged in conduct that is fraudulent, deceitful, unlawful or is or could be a threat to persons or property.</p><br/>
<p align="justify"><b>Proprietary Rights</b><br/><br/>
The Site and all material published on the Site, including, but not limited to text, photographs, video, text, graphics, music, sounds, messages, comments, ratings, and other materials is owned by Momburbia or its licensors and is protected by copyright, patents, trademarks, trade secrets and/or other proprietary rights, under the Canadian copyright laws. Momburbia owns a copyright in the selection, coordination, arrangement and enhancement of such content and a copyright in the Site.
</p><br/>
<p align="justify">All trademarks appearing on this Site ("Marks") are trademarks of their respective owners, including Momburbia and its partners. Users are prohibited from using any Marks without the written permission of Momburbia or such third party that may own the Marks.</p><br/>
<p align="justify">Content on the Site is provided AS IS for your information and personal use only. You may not copy, publish, transmit, distribute, perform, sell, create derivative works of, or in any way exploit, any of the content, in whole or in part, without Momburbia's prior written consent. You may download content for your personal, non-commercial use only as provided in these TOS, provided that you keep intact all copyright and other proprietary notices. Copying or storing of content for other than personal use is expressly prohibited without prior permission from us or the copyright holder identified in the copyright notice contained in the content.</p><br/>
<p align="justify"><b>No License Granted.</b><br/><br/>
Except for allowing you to use the Site for your personal use as set forth in the paragraph above, when you use the Site, you are not receiving a license or any other rights from us, including intellectual property or other proprietary rights of Momburbia. YOU UNDERSTAND THAT YOU HAVE NO RIGHTS TO THE SERVICES OR ANY OTHER MOMBURBIA PROPERTY EXCEPT AS WE INDICATE IN THESE TERMS.
</p><br/>
<p align="justify"><b>Age Requirements.</b><br/><br/>
You must be at least 16 years old to join Momburbia and to use the Services. The Momburbia Site and Services is not intended for children under the age of 16. Momburbia does not knowingly collect personal information from children under the age of 16.
</p><br/>
<p align="justify"><b>Communications from Momburbia.</b><br/><br/>
By registering for Momburbia, you will receive online communications from Momburbia. To unsubscribe from any Momburbia email list, simply click on the "Unsubscribe" link at the bottom of the email and your name will be removed from that mailing list.
</p><br/>
<p align="justify"><b>Links.</b><br/><br/>
The Site, or Members, may provide links to other World Wide Web sites or resources. Because Momburbia has no control over such sites and resources, you acknowledge and agree that Momburbia is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for any content, advertising, products or other materials or available from such sites or resources. You further acknowledge and agree that Momburbia shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such site or resource.
</p><br/>
<p align="justify"><b>Indemnity.</b><br/><br/>
You understand that you are personally responsible for your behavior while on the Site and agree to indemnify and hold Momburbia, and its affiliates, business partners, and their respective officers, directors, employees, and agents, harmless from and against any loss, damage, liability, cost, or expense of any kind (including attorneys' fees) that we may incur in connection with a third party claim or otherwise, in relation to your use of the Services or access to the Site, or your violation of either these TOS, applicable law or the rights of any third party.
</p><br/>
<p align="justify"><b>Disclaimer of Warranties.</b><br/><br/>
YOU UNDERSTAND THAT YOUR USE OF THE SITE AND SERVICES (INCLUDING ANY DOWNLOADS OR ANY LOSS OF DATA OR OTHER DAMAGE TO YOUR COMPUTER SYSTEM YOU EXPERIENCE FROM USING THE SITE AND SERVICES) IS AT YOUR SOLE RISK. YOU UNDERSTAND THAT THE SITE AND SERVICES AND ALL INFORMATION, PRODUCTS AND OTHER CONTENT (INCLUDING THIRD PARTY INFORMATION, PRODUCTS AND CONTENT INCLUDED IN OR ACCESSIBLE FROM THE SITE OR SERVICES, ARE PROVIDED ON AN "AS IS" "WHERE-IS" AND "WHERE AVAILABLE" BASIS, AND ARE SUBJECT TO CHANGE AT ANY TIME WITHOUT NOTICE TO YOU. YOU ACKNOWLEDGE THAT MOMBURBIA MAKES NO WARRANTY THAT THE SITE OR SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE. YOU UNDERSTAND THAT MOMBURBIA DOES NOT WARRANT THAT THE RESULTS OBTAINED FROM YOUR USE OF THE SITE OR SERVICES WILL MEET YOUR EXPECTATIONS. NO WARRANTY OF ANY KIND, WHETHER ORAL OR WRITTEN, CAN MODIFY THE TERMS OF THE DISCLAIMER SET FORTH IN THIS DOCUMENT.
</p><br/>
<p align="justify">YOUR USE AND BROWSING OF THE SITE IS AT YOUR OWN RISK. IF YOU ARE DISSATISFIED WITH ANY OF THE MATERIALS CONTAINED IN THE SITE OR SERVICES, OR WITH ANY OF THESE TOS, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE ACCESSING AND USING THE SITE AND SERVICES.</p><br/>
<p align="justify">TO THE FULLEST EXTENT PERMITTED BY LAW, MOMBURBIA DISCLAIMS ALL REPRESENTATIONS, WARRANTIES, AND CONDITIONS OF ANY KIND (EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS) AS TO THE SITE AND SERVICES AND ALL INFORMATION, PRODUCTS, AND OTHER CONTENT (INCLUDING THIRD PARTY INFORMATION, PRODUCTS, AND CONTENT) INCLUDED IN OR ACCESSIBLE FROM THE SITE AND SERVICES.</p><br/>
<p align="justify">THE INFORMATION IS PROVIDED WITH THE UNDERSTANDING THAT MOMBURBIA IS NOT ENGAGED IN RENDERING LEGAL, MEDICAL, FINANCIAL, COUNSELING, OR OTHER PROFESSIONAL SERVICES OR ADVICE. MOMBURBIA ENCOURAGES YOU TO SEEK APPROPRIATE PROFESSIONAL ADVICE OR CARE REGARDING ANY SITUATION THAT REQUIRES SUCH ATTENTION.</p><br/>
<p align="justify"><b>Liability Disclaimer.</b><br/><br/>
TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL MOMBURBIA OR ITS AFFILIATES BE LIABLE TO YOU (OR ANY THIRD PARTY MAKING CLAIMS THROUGH YOU) FOR ANY DAMAGES WHATSOEVER, INCLUDING BUT NOT LIMITED TO ANY DIRECT, INDIRECT, SPECIAL, CONSEQUENTIAL, PUNITIVE OR INCIDENTAL DAMAGES, OR DAMAGES FOR LOSS OF USE, PROFITS, DATA, OR OTHER INTANGIBLES, OR THE COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, UNAUTHORIZED ACCESS TO AND TAMPERING WITH YOUR PERSONAL INFORMATION OR TRANSMISSIONS, ARISING OUT OF OR RELATED TO THE USE, INABILITY TO USE, UNAUTHORIZED USE, PERFORMANCE, OR NON-PERFORMANCE OF THE SITE OR THE SERVICES, EVEN IF MOMBURBIA HAS BEEN ADVISED PREVIOUSLY OF THE POSSIBILITY OF SUCH DAMAGES AND WHETHER SUCH DAMAGES ARISE IN CONTRACT, NEGLIGENCE, TORT, UNDER STATUTE, IN EQUITY, AT LAW, OR OTHERWISE.
</p><br/>
<p align="justify">If any part of these warranty disclaimers or limitations of liability is found to be invalid or unenforceable for any reason, then our aggregate liability for all claims under such circumstances for liabilities shall not exceed ten dollars ($10).</p><br/>
<p align="justify"><b>Access Restrictions; Termination.</b><br/><br/>
We can suspend or terminate your membership in Momburbia and your access to the Site or the Services, in whole or in part, at any time, immediately and without notice if, at Momburbia's sole discretion, you fail to comply with any of the TOS or the <a href='/index.php/help/guide'>Community Guidelines</a>. Upon termination, you must destroy all materials obtained from this Site and the Services and all copies thereof. In the event of suspension or termination, you are no longer authorized to access the Site or the Services, and the restrictions imposed on you with respect to any materials downloaded from the Site or the Services and the disclaimers and limitations of liabilities set forth in the TOS shall survive.
</p><br/>
<p align="justify">You understand and agree that your membership in Momburbia is subject to and conditioned upon the following: Your continued adherence to these TOS and the Community Guidelines and any future modifications thereto. Your violation of these TOS, the Community Guidelines, or any other agreement between you and Momburbia constitute grounds for immediate termination of your membership without further notice at Momburbia's sole discretion. We may also terminate your membership at any time, immediately and without notice, if we determine, in our sole discretion, that your conduct is detrimental to our business or the Momburbia community. Termination of your membership will result in cancellation of all rights of access and use granted to Members. Momburbia reserves the right to change, discontinue or suspend Momburbia or any of the Services at any time for any reason. Members may terminate their membership at any time by sending their request to us, using the "Contact Us" button on any page of the Site. Momburbia shall be the sole determiner in cases of suspected abuse, fraud, or breach of these TOS or the <a href='/index.php/help/guide'>Community Guidelines</a>. Any decision Momburbia makes relating to termination or suspension of any Member's account shall be final and binding. Momburbia may terminate any Member's account at its sole discretion if a Member has been inactive for a period of twelve (12) months. A Member will be defined as inactive if she has not logged into the Site, or contacted Momburbia in any other manner. In addition, if you have been inactive for three (3) months, we may take down any photos that you have posted to your profile or anywhere else on the Site.</p><br/>
<p align="justify"><b>Digital Millennium Copyright Act ("DMCA") Notice.</b><br/><br/>
Materials may be made available via the Site and the Services by third parties not within our control. We are under no obligation to, and do not, scan content posted, however, we respect the copyright interests of others. It is our policy not to permit materials known by us to infringe another party's copyright to remain on the Site or the Service.
</p><br/>
<p align="justify">If you believe any materials on the Site or the Service infringe a copyright, you should provide us with written notice that at a minimum contains:</p><br/>
<ol>
	<li>A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;
	<li>Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site;
	<li>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material;
	<li>Information reasonably sufficient to permit us to contact the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which the complaining party may be contacted;
	<li>A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and
	<li>A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.
</ol><br/>
<p align="justify">All DMCA notices should be sent to our designated agent utilizing our contact form</p><br/>
<p align="justify"><b>Third Party Products and Services.</b><br/><br/>
You may order services, merchandise or other products through our Site from other parties (collectively, the "Third Party Sellers"). All matters concerning the services, merchandise and other products desired from the Third Party Sellers including, but not limited to, purchase terms, payment terms, warranties, guarantees, maintenance and delivery, are solely between you and the Third Party Sellers. We make no warranties or representations whatsoever with regard to any services, merchandise or other products provided by the Third Party Sellers. You will not consider us (and we will not be construed as) a party to such transaction, whether or not we may have received some form of revenue or other remuneration in connection with such transactions, and we will not be liable for any costs or damages arising out of, either directly or indirectly, you or any other person involved or related to the transactions.
</p><br/>
<p align="justify"><b>Momburbia Inc. Employees, Partners and Investors.</b><br/><br/>
Our employees are dedicated to building the best social networking site for moms and providing you with the tools that you need to have a great online experience. In connection with their work, some of our employees are required to use the Site, including creating a profile. Our advertisers, partners and investors may also use the Site and the Services, including creating a profile, for business and advertising purposes.
</p><br/>
<p align="justify"><b>Miscellaneous.</b><br/><br/>
These TOS are the entire agreement between you and Momburbia. They supersede any and all prior or contemporaneous agreements between you and Momburbia relating to your use of the Site or the Services. If any part of these TOS is determined to be invalid or unenforceable, it will not impact any other provision of these TOS, all of which will remain in full force and effect. The failure of Momburbia to partially or fully exercise any rights or the waiver of Momburbia of any breach of these TOS by you, shall not prevent a subsequent exercise of such right by Momburbia or be deemed a waiver by Momburbia of any subsequent breach by you of the same or any other term of these TOS. The rights and remedies of Momburbia under these TOS and any other applicable agreement between you and Momburbia shall be cumulative, and the exercise of any such right or remedy shall not limit Momburbia's right to exercise any other right or remedy.
</p><br/>
<p align="justify"><b><font color="red">These TOS are governed by, and will be interpreted in accordance with, the laws of the Province of Ontario, without regard to any choice of law provisions. You agree that, with the exception of injunctive relief sought by Momburbia for any violation of Momburbia's proprietary or other rights, any and all disputes relating to these TOS, your use of the Site or the Services shall be resolved by arbitration before an independent arbitrator.  The location of arbitration shall be Toronto, Ontario, Canada.</font></b></p><br/>
<p align="justify"><b>The Momburbia website is owned and operated Momburbia, Inc. which also owns the Momburbia trademark. </b></p><br/>
<p align="justify"><b></b></p><br/>

</div>
</div>