<?php
/**
 * SocialEngine
 *
 * @category   Application_Core
 * @package    Core
 * @copyright  Copyright 2006-2010 Webligo Developments
 * @license    http://www.socialengine.net/license/
 * @version    $Id: terms.tpl 7244 2010-09-01 01:49:53Z john $
 * @author     John
 */
?>
<div class='global_form_popup' style='width: 800px;'>
<h2><?php echo $this->translate('OFFICIAL CANADIAN AND UNITED STATES "Moms 1K Holiday" PROMOTION RULES 2011') ?></h2>

<h3>NO PURCHASE IS NECESSARY</h3>
<br/>
<div class="rules">
<p align="justify">Online Entries shall be referred to herein as "Entries" collectively. Entries become the property of Sponsor and will not be returned or acknowledged. Information on how to enter and prizes form part of these official rules ("Official Rules").</p><br/><br/>
<p align="justify"><b>SPONSOR</b></p><br/>
Sponsor is Momburbia Inc.
<br/><br/>
<p align="justify"><b>1.  WHO MAY ENTER </b><br/><br/>
Contest is open only to legal residents of the United States (excluding residents of Puerto Rico) and Canada (excluding Quebec) who are above the age of 16. Employees of Sponsor, and their affiliates and subsidiaries, and their immediate family members (spouse, parent, child, sibling and their respective spouses, regardless of where they live) or persons living in the same households of such individuals, whether or not related, are not eligible to enter or win a prize. CONTEST IS VOID IN PUERTO RICO AND QUEBEC AND WHERE PROHIBITED.
</p><br/><br/>
<p align="justify"><b>2.  HOW TO ENTER:</b><br/><br/>
The <b>Momburbia</b>&reg; Mom 1K Holiday (the "Promotion") commences at 9:00 AM (ET) on February 1, 2011 and ends at 5:30 PM (ET) on February 28th, 2011 (the "Promotion Period"). There is one way to enter:

<ol>
<li type="a">Visit <a href="/">www.momburbia.com</a>.  You will be required to register on the <b>Momburbia</b> website to become a member of the <b>Momburbia</b> community to receive access to <b>Momburbia</b> website features.  Begin by entering your email address, entering and confirming a password, entering a profile address, selecting your language, enter the security code found on the webpage, indicate that you have read and agree to the terms of service and select the "Continue" icon.  Now enter your first name, last name, date of birth, city and country and click save. Upload a photo if you wish or click skip.  Invite friends to <b>Momburbia</b> by using the email import invite feature or skip.  You have now become a member of the <b>Momburbia</b> community and can visit the <b>Momburbia</b> Contest group page to enter the promotion.  Either click on the Contest tab and be redirected to the <b>Momburbia</b> Contest Group, find a banner advertisement and click on it to be redirected to the <b>Momburbia</b> Contest Group or click on the Groups tab that will take you directly to the <b>Momburbia</b> Contest Group.  Click to join the group.  Once you have joined, type in why you should win the promotion as this is considered your entry in the random draw.  </li>
<li type="a">Existing members of the <b>Momburbia</b> community who have previously registered at <a href="/">www.momburbia.com</a>, can enter the Promotion by logging in, joining the Momburbia Contest Group and posting on the update wall a reason of why they should win.  By entering they have read, understood, and accept the Official Rules.  Entries must be received by 5:30 PM (ET) on February 28th, 2011 (the "Promotion Closing Date").<b>OR</b></li>
<li type="a">Login to use your Facebook account with MomburbiaConnect.  Click on the f Connect with Facebook button on the homepage of www.momburbia.com.  Type in your email address and password that you use for your Facebook account, chose to keep yourself logged in and click Login button on the bottom right corner.  You will be directed to create an account with your Facebook email address populated and also your profile address populated.  Modify your profile address to your liking but do not change your email address.  Click "Continue" to indicate that you have read and agree to the terms of service.  You will land on a page where you can either type in or modify your first name, last name, date of birth, city and country.  Ensure all information has been filled in and click on the "save" icon.  You will be promted to publish your story to your Facebook.  If you wish not to publish, select "No, do not publish".  You will be able to invite your Facebook friends to join the site at this time.  If you wish to enter the contest, either click on the Contest tab and be redirected to the <b>Momburbia</b> Contest Group, find a banner advertisement and click on it to be redirected to the <b>Momburbia</b> Contest Group or click on the Groups tab that will take you directly to the <b>Momburbia</b> Contest Group.  Click to join the group.  Once you have joined, type in why you should win the promotion as this is considered your entry in the random draw.</li>

</ol>
<br/>
<b>Limit one entry per member</b>. A day is defined as commencing at 12:00 AM (ET) on ending at 11:59 PM (ET). Any member who has entered more than once per day will be disqualified and all entries received from such member during the Promotion Period will be disqualified. Proof of transmission (screenshots or captures, etc.) does not constitute proof of delivery. Entries generated by script, macro, robotic, programmed, or any other automated means are prohibited and will be disqualified.
</p><br/><br/>
<p align="justify"><b>3.PRIZE:</b><br/><br/>
One Grand Prize is available to be won consisting of a $1000.00 cheque.  The Winner must provide proof that they are a resident of Canada or the United States upon winning and that they are above the age of 16.  The Winner must provide valid contact information in order for them to be contacted through email or phone for the prize to be awarded.  The Winner is responsible for all taxes and expenses not specified herein. The Grand Prize must be accepted as awarded without substitution and is not transferable.  In the event the Sponsor is unable to award the Grand Prize or any component thereof as described for any reason, the Sponsor reserves the right to substitute the Grand Prize or any component of the Grand Prize with another prize of equal or greater value, without liability.
</p><br/><br/>
<p align="justify"><b>4. RANDOM DRAW:</b><br/><br/>
A random draw will be conducted by an independent contest organization on March 28, 2011 (the "Draw Date") at 10:00 AM (ET) in Markham, ON, amongst all eligible entries received. Odds of being selected for the Grand Prize depends on the total number of eligible entries received during the Promotion Period. The selected entrant will be contacted by email within 10 business days of the Draw Date. If the selected entrant cannot be contacted within the time frame indicated above, his/her entry will be disqualified and another entrant will be randomly selected from the remaining eligible entries and the process above will be repeated until such time as contact is made with a selected entrant or there are no more eligible entrants. Prior to being declared a winner, the selected entrant must first correctly answer without assistance of any kind, whether mechanical or otherwise, a mathematical skill-testing question posed by mail or telephone at a mutually convenient time within 10 business days of the Draw Date. In the event that a selected entrant incorrectly answers the mathematical skill-testing question, he/she will be disqualified and another entrant will be randomly selected and the above process will be repeated until such time as there is one confirmed winner or no more eligible entries are available.
</p><br/><br/>
<p align="justify"><b>5. ENTRANT LICENSES/RELEASES</b><br/><br/>
By entering the promotion, the winner grant a royalty-free, irrevocable, perpetual, non-exclusive license to Sponsor, its designees, licensees and affiliates ("Authorized Parties"), to reproduce, distribute, display and create derivative works of the photographs (along with a name credit) in connection with the Promotion and promotion of the Promotion, in any media now or hereafter known, including, but not limited to: Display at a potential exhibition of winner; publication of a book featuring select entries in the Promotion; publication online highlighting entries or winner of the Promotion. Entrants further hereby waive all moral rights in and to the entries in favor of the Sponsor. Authorized Parties will not be required to pay any additional consideration or seek any additional approval in connection with such use.
</p><br/><br/>
<p align="justify"><b>6. LIMITATION OF LIABILITY</b><br/><br/>
By participating, entrants agree to release, discharge and hold harmless Sponsor, their partners, affiliates, subsidiaries, agents and their employees, officers, directors, and representatives from any claims, losses, and damages arising out of their participation in this Contest or any Contest-related activities and the acceptance and use, misuse, or possession of any prize awarded hereunder. 
</p><br/><br/>
<p align="justify"><b>7. CONDITIONS </b><br/><br/>
This Contest is subject to federal, state, provincial, territorial and local laws and regulations. Certain restrictions may apply. Sponsor is not responsible for late, lost, stolen, damaged, mutilated, incomplete, illegible, misdirected, or postage-due mail. Entries void if the Sponsor determines the entry to not be an original, or if the entries are illegible, incomplete, damaged, irregular, altered, counterfeit, produced in error or obtained through fraud or theft. 
<br/><br/>
Entrants also agree (a) to be bound by these Official Rules; (b) that the decisions of the judges are final on all matters relating to the Contest; and (c) if he/she wins that Sponsor may use the winning photograph and each winner’s name, photograph, likeness, and/or voice in any publicity or advertising relating to the Contest or future promotions without compensation or approval (except in Tennessee and where prohibited by law). All taxes, fees and surcharges on prizes are the sole responsibility of the prize winners. In the event that the selected winner(s) of any prize are/is ineligible or refuses the prize, the prize will be forfeited and Sponsor, in its sole discretion, may choose whether to award the prize to another winner.
</p><br/><br/>
<p align="justify"><b>8.  WINNERS' LIST </b><br/><br/>
Grand Prize winner name (First and last name, and city of residence) will be available online at Momburbia.com.
</p><br/><br/>
<p align="justify"><b>9.  RELEASE FORM:</b><br/><br/>
Prior to being declared a Winner and receiving the Grand Prize, the selected entrant will be required to sign a Declaration and Publicity Release Form (the "Release Form"). By completing and returning the Release Form, the Winner confirms compliance with the Official Rules, accepts the Grand Prize as awarded, without substitution, releases the Releasees from all liability relating to the Promotion and/or to a Prize (as specified more fully in Rule 6, below), and consents to the use of his/her name, address (city and province) and/or photographs, without additional compensation, in connection with any publicity carried out by or on behalf of the Sponsor with respect to the Promotion. The signed Release Form must be returned within the time period specified on the Release Form or the Grand Prize will be forfeited and another entrant will be selected, and the process above will be repeated until such time that there is one confirmed Prize Winner or no more eligible entries are available. Upon receipt of the completed Release Form, the Sponsor or a designated agent will contact the Winner within ten days to begin making the necessary delivery arrangements as defined in Rule 4 above.
</p><br/><br/>
<p align="justify"><b>10.  GENERAL:</b><br/><br/>
By entering the Promotion, entrants agree to read, abide and be bound by the Official Rules, including all eligibility requirements and by the decisions of the independent contest organization, made in its sole discretion, which shall be final and binding in all matters relating to the Promotion. Entrants who have not complied with the Official Rules are subject to disqualification.
<ul>
<li>By entering the Promotion and, if applicable, completing the Release Form, the entrant agrees to release and hold harmless the Sponsor, its affiliated and related companies, business partners, advertising and promotional agencies, prize suppliers, and the independent contest organization, and each of their respective directors, officers, employees, agents, representatives, successors and assigns and all others associated with the development and execution of the Promotion (collectively, the "Releasees"), from and against any and all manner of action, causes of action, suits, debts, covenants, contracts, claims and demands, including legal fees and expenses, whatsoever, including but not limited to, claims based on negligence, breach of contract, and fundamental breach and liability for physical injury, death, or property damage which an entrant or his/her administrators, heirs, successors, or assigns might have or could have, by reason of or arising out of the selected entrant's participation in the Promotion and/or in connection with the acceptance or use of the Grand Prize.</li>
<li>The Sponsor and the independent contest organization do not assume any responsibility and are not responsible for (i) the incorrect or inaccurate capture of entry information and entries that fail to comply with the Official Rules; (ii) any loss, damage, or claims caused by the Grand Prize or the Promotion itself; or (iii) any failure of the website during the Promotion Period, including any problems, human or technical errors, printing or typographical errors, lost, delayed or garbled data or transmissions, omissions, interruptions, deletions, defects or failures of any telephone or computer lines or networks, technical malfunctions of any computer on-line systems, computer equipment, servers, access providers, software, failure of any e-mail or entry to be received on account of technical problems or traffic congestion on the Internet or at any website, or any combination thereof including any injury or damage to an entrant's or any other person's computer relating to or resulting from downloading any material connected to the Promotion, all of which may affect a person's ability to participate in the Promotion. The Sponsor and the independent contest organization do not assume any responsibility and are not responsible for electronic communications which are undeliverable as a result of any form of active or passive filtering of any kind or insufficient space in an entrant's mailbox to receive e-mail messages, or for late, lost, illegible, incomplete, falsified, damaged, misdirected, mutilated, garbled, or incomplete entries, which will be void. Entry materials/data that have been tampered with or altered are void. Any attempt to deliberately damage any website or to undermine the legitimate operation of the Promotion is a violation of criminal and civil laws. Should such an attempt be made, the Sponsor reserves the right to seek remedies and damages to the fullest extent permitted by law, including criminal prosecution, and to disqualify an entrant from the Promotion or any other promotion conducted by the Sponsor now or in the future. In the event it is determined that an entrant has entered the Promotion in a manner contrary to the Official Rules and/or has submitted more than the number of entries permitted by the Official Rules, the entrant and all of the entries submitted by the entrant will be disqualified. If, due to any technical, production or other error, more prizes are claimed or awarded than are described in the Official Rules, the number of prizes identified in the Official Rules will be awarded in a random drawing from all such prize claims received. In no event will the Sponsor be responsible or liable for more than the stated number of prizes described in the Official Rules.</li>
<li>In the event of a dispute as to the identity of an entrant, entries made on-line will be deemed to have been made by the authorized account holder of the e-mail address submitted at the time of entry. An "authorized account holder" is defined as the natural person assigned to an e-mail address by an Internet service provider, on-line service provider, or other organization responsible for assigning e-mail addresses for the domain associated with the submitted e-mail addresses. The potential Winner may be required to show proof of being the authorized account holder for the e-mail address associated with the winning entry.</li>
<li>All entries become the property of the Sponsor and none will be returned. No correspondence will be entered into except with the selected entrant and the Winner. The Promotion is subject to all applicable Federal, Provincial and Municipal laws. The Promotion is void where prohibited by law. All issues and questions concerning the construction, validity, interpretation, and enforceability of the Official Rules, or the rights and obligations of entrants and the Sponsor in connection with the Promotion, shall be governed by and construed in accordance with (i) the laws of Canada and (ii) the laws of the Province of Ontario and the laws of Canada applicable therein in respect of residents of the other Canadian provinces/territories, without regard to conflicts of law principles.</li>
</ul>
</p><br/><br/>
<p align="justify"><b>11. PRIVACY:</b><br/><br/>
The Sponsor respects each entrant's right to privacy. By entering the Promotion and voluntarily providing personal information, entrants consent and agree to the Sponsor's collection and use of entrants' information for the administration of the Promotion in accordance with the applicable privacy policies of Momburbia Inc. available at http://www.momburbia.com. Personal information collected in relation to the Promotion will be destroyed following the Promotion and awarding of the Grand Prize. However, if an entrant consents to receive future information from Momburbia, Momburbia may use the information provided to initiate, maintain and develop a relationship with the entrant in connection with offering any of Momburbia Inc. products; or to promote and market to the entrant additional products and services offered by Momburbia Inc. 
</p><br/>

<p>
<a href="javascript:void(0);" onclick="parent.Smoothbox.close();">
          <?php echo $this->translate("close") ?>
        </a>
</p>
</div>
</div>